-- 0010_readable_ids_batches.sql
-- V3: human-readable IDs + course batches, requested directly by the user.
-- None of this is in the ERD — same documented-extension pattern as
-- 0006_extensions.sql and 0009_profile_settings.sql. The real PKs
-- (studentid/teacherid/adminid/courseid, all uuid) are untouched; these
-- are additional display-only columns plus one small new table.

-- ============ Part 1: human-readable IDs ============
-- S00001 / T00001 / A00001 style codes, generated by role via a
-- per-role sequence + BEFORE INSERT trigger, never user-editable.

alter table public.students add column if not exists display_id text unique;
alter table public.teachers add column if not exists display_id text unique;
alter table public.admins add column if not exists display_id text unique;

create sequence if not exists public.student_display_seq;
create sequence if not exists public.teacher_display_seq;
create sequence if not exists public.admin_display_seq;

create or replace function public.set_student_display_id()
returns trigger language plpgsql as $$
begin
  if new.display_id is null then
    new.display_id := 'S' || lpad(nextval('public.student_display_seq')::text, 5, '0');
  end if;
  return new;
end;
$$;

create or replace function public.set_teacher_display_id()
returns trigger language plpgsql as $$
begin
  if new.display_id is null then
    new.display_id := 'T' || lpad(nextval('public.teacher_display_seq')::text, 5, '0');
  end if;
  return new;
end;
$$;

create or replace function public.set_admin_display_id()
returns trigger language plpgsql as $$
begin
  if new.display_id is null then
    new.display_id := 'A' || lpad(nextval('public.admin_display_seq')::text, 5, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_student_display_id on public.students;
create trigger trg_student_display_id before insert on public.students
  for each row execute function public.set_student_display_id();

drop trigger if exists trg_teacher_display_id on public.teachers;
create trigger trg_teacher_display_id before insert on public.teachers
  for each row execute function public.set_teacher_display_id();

drop trigger if exists trg_admin_display_id on public.admins;
create trigger trg_admin_display_id before insert on public.admins
  for each row execute function public.set_admin_display_id();

-- Backfill any rows that existed before this migration, oldest first so
-- IDs read as a natural signup order, then fast-forward each sequence
-- past the backfilled count so new signups never collide with them.
do $$
declare
  cnt int;
begin
  update public.students s set display_id = sub.code
  from (
    select studentid, 'S' || lpad(row_number() over (order by studentid)::text, 5, '0') as code
    from public.students where display_id is null
  ) sub
  where s.studentid = sub.studentid;
  select count(*) into cnt from public.students;
  perform setval('public.student_display_seq', cnt, true);

  update public.teachers t set display_id = sub.code
  from (
    select teacherid, 'T' || lpad(row_number() over (order by teacherid)::text, 5, '0') as code
    from public.teachers where display_id is null
  ) sub
  where t.teacherid = sub.teacherid;
  select count(*) into cnt from public.teachers;
  perform setval('public.teacher_display_seq', cnt, true);

  update public.admins a set display_id = sub.code
  from (
    select adminid, 'A' || lpad(row_number() over (order by adminid)::text, 5, '0') as code
    from public.admins where display_id is null
  ) sub
  where a.adminid = sub.adminid;
  select count(*) into cnt from public.admins;
  perform setval('public.admin_display_seq', cnt, true);
end $$;

-- ============ Part 2: course codes ============
alter table public.courses add column if not exists course_code text unique;

create sequence if not exists public.course_code_seq;

create or replace function public.set_course_code()
returns trigger language plpgsql as $$
begin
  if new.course_code is null then
    new.course_code := 'C' || lpad(nextval('public.course_code_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_course_code on public.courses;
create trigger trg_course_code before insert on public.courses
  for each row execute function public.set_course_code();

do $$
declare cnt int;
begin
  update public.courses c set course_code = sub.code
  from (
    select courseid, 'C' || lpad(row_number() over (order by courseid)::text, 4, '0') as code
    from public.courses where course_code is null
  ) sub
  where c.courseid = sub.courseid;
  select count(*) into cnt from public.courses;
  perform setval('public.course_code_seq', cnt, true);
end $$;

-- ============ Part 3: course batches ============
-- A batch is a scheduled cohort/intake of a course — lets the same course
-- run multiple times with its own start date, seat count, and enrollment
-- deadline, and gives enrollment a real, non-fabricated basis for urgency
-- CTAs ("Batch 3 — 4 seats left" / "closes in 3 days") instead of making
-- up a seasonal sale.

create table public.course_batches (
  batchid uuid primary key default gen_random_uuid(),
  courseid uuid not null references public.courses(courseid) on delete cascade,
  batch_number int not null,
  batch_code text not null,
  starts_on date,
  seats_total int,
  enrollment_deadline date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (courseid, batch_number)
);

alter table public.course_batches enable row level security;
create policy "read batches" on public.course_batches for select using (true);
create policy "admin writes batches" on public.course_batches
  for all using (public.current_app_role() = 'admin');

-- Enrollment optionally ties to a specific batch. Nullable: existing
-- enrollments and any course without batches configured stay valid.
alter table public.enrollments add column if not exists batchid uuid references public.course_batches(batchid) on delete set null;
