INSERT INTO public.vocab_words (word, definition, example, difficulty) VALUES

-- SUBLIST 1 (most frequent academic words)
('analyse', 'Examine in detail to understand or explain', 'Scientists analyse data to identify patterns.', 'easy'),
('approach', 'A way of dealing with a situation or problem', 'The government took a new approach to education policy.', 'easy'),
('area', 'A subject or range of activity', 'Research in this area has grown significantly.', 'easy'),
('assess', 'Evaluate or estimate the nature or quality of something', 'Teachers assess students through both exams and coursework.', 'easy'),
('assume', 'Accept as true without proof', 'The study assumes that all participants were equally motivated.', 'medium'),
('authority', 'The power or right to give orders or make decisions', 'Local authorities are responsible for waste management.', 'easy'),
('available', 'Able to be obtained or used', 'Data is available online for public access.', 'easy'),
('benefit', 'An advantage or profit gained from something', 'Exercise has numerous benefits for mental health.', 'easy'),
('concept', 'An abstract idea or general notion', 'The concept of sustainability underpins modern urban planning.', 'medium'),
('consistent', 'Acting or done in the same way over time', 'Results must be consistent across multiple trials.', 'medium'),
('context', 'The circumstances surrounding an event or idea', 'Language must be understood in its cultural context.', 'medium'),
('contract', 'A formal written agreement', 'The company signed a contract with the supplier.', 'easy'),
('create', 'Bring something into existence', 'The project aims to create 500 new jobs.', 'easy'),
('data', 'Facts and statistics collected for analysis', 'The data clearly shows a rise in global temperatures.', 'easy'),
('define', 'State the exact meaning of a word or concept', 'It is essential to clearly define the research objectives.', 'easy'),
('derive', 'Obtain something from a specified source', 'Many English words are derived from Latin.', 'medium'),
('distribute', 'Supply goods or spread something over an area', 'Leaflets were distributed to local residents.', 'easy'),
('economy', 'The system of trade and production in a region', 'The economy grew by 3% last year.', 'easy'),
('environment', 'The natural world or surroundings', 'Protecting the environment is a global responsibility.', 'easy'),
('establish', 'Set up or bring into existence on a firm basis', 'The university was established in 1850.', 'easy'),
('estimate', 'Roughly calculate or judge the value of something', 'Researchers estimate that 40% of species face extinction.', 'easy'),
('evidence', 'Facts indicating whether a belief is true or valid', 'There is strong evidence linking diet to heart disease.', 'easy'),
('export', 'Send goods or services to another country', 'The country exports over 60% of its agricultural produce.', 'easy'),
('factors', 'Things that contribute to a result', 'Several factors influence academic achievement.', 'easy'),
('financial', 'Relating to finance or money', 'The company faced serious financial difficulties.', 'easy'),
('formula', 'A mathematical rule expressed in symbols', 'Einstein''s formula E=mc² changed physics forever.', 'medium'),
('function', 'The purpose or role something serves', 'The function of the immune system is to fight disease.', 'easy'),
('identify', 'Establish the identity or nature of something', 'The study identified three key risk factors.', 'easy'),
('income', 'Money received regularly for work or investments', 'Average household income has risen steadily.', 'easy'),
('indicate', 'Point out or show something', 'The results indicate a strong correlation.', 'easy'),
('individual', 'A single human being or item', 'Each individual is responsible for their own learning.', 'easy'),
('interpret', 'Explain the meaning of something', 'It is important to interpret data carefully.', 'medium'),
('involve', 'Include or require as a part', 'The project involves collaboration between three departments.', 'easy'),
('issue', 'An important topic or problem for discussion', 'Climate change is the defining issue of our time.', 'easy'),
('labour', 'Work, especially physical work', 'Child labour is prohibited by international law.', 'easy'),
('legal', 'Permitted by law', 'The company took legal action against the supplier.', 'easy'),
('legislate', 'Make laws', 'Parliament legislated to ban single-use plastics.', 'medium'),
('major', 'Important, serious or significant', 'Air pollution is a major concern in urban areas.', 'easy'),
('method', 'A particular procedure for accomplishing something', 'The scientific method involves observation and testing.', 'easy'),
('occur', 'Happen or take place', 'Climate events occur more frequently due to global warming.', 'easy'),
('percent', 'A rate or proportion per hundred', 'Forty percent of adults are not meeting exercise guidelines.', 'easy'),
('period', 'A length or portion of time', 'The Industrial Revolution was a significant period in history.', 'easy'),
('policy', 'A set of principles adopted by a government or organisation', 'The government introduced a new housing policy.', 'easy'),
('principle', 'A fundamental truth or rule', 'The principle of democracy underpins many constitutions.', 'medium'),
('procedure', 'An established way of doing something', 'Follow the correct procedure when handling chemicals.', 'medium'),
('process', 'A series of actions to achieve a result', 'The process of photosynthesis converts sunlight into energy.', 'easy'),
('required', 'Made necessary by regulations or circumstances', 'A passport is required for international travel.', 'easy'),
('research', 'Systematic investigation to establish facts', 'Research into renewable energy has accelerated.', 'easy'),
('response', 'A reaction to something', 'The government''s response to the crisis was widely criticised.', 'easy'),
('role', 'The function played by a person or thing', 'Education plays a vital role in economic development.', 'easy'),
('section', 'A distinct part of something', 'The reading test has three sections.', 'easy'),
('significant', 'Sufficiently great to be noteworthy', 'There was a significant rise in unemployment.', 'easy'),
('similar', 'Resembling without being identical', 'The two studies produced similar results.', 'easy'),
('source', 'A place or person from which something comes', 'Fossil fuels remain the primary source of energy worldwide.', 'easy'),
('specific', 'Clearly defined or identified', 'Please give specific examples to support your argument.', 'easy'),
('structure', 'The arrangement of parts in something', 'The structure of DNA was discovered in 1953.', 'medium'),
('theory', 'An explanation based on evidence and reasoning', 'Darwin''s theory of evolution is supported by fossil evidence.', 'medium'),
('vary', 'Differ in size, amount or nature', 'Test scores vary considerably between schools.', 'easy'),

-- SUBLIST 2
('achieve', 'Successfully reach a desired objective', 'Hard work is required to achieve a high band score.', 'easy'),
('acquire', 'Come to have or obtain something', 'Children acquire language remarkably quickly.', 'medium'),
('administrate', 'Manage or direct the running of a business or organisation', 'The ministry administrates all public schools.', 'hard'),
('affect', 'Have an effect on; make a difference to', 'Pollution affects the health of urban populations.', 'easy'),
('appropriate', 'Suitable or proper in the circumstances', 'Choose vocabulary that is appropriate for academic writing.', 'medium'),
('aspect', 'A particular part or feature', 'Climate change affects every aspect of daily life.', 'easy'),
('assist', 'Help someone', 'Technology can assist students with learning difficulties.', 'easy'),
('category', 'A group of people or things with shared characteristics', 'The results fell into three distinct categories.', 'easy'),
('chapter', 'A main division of a book', 'The final chapter discusses policy implications.', 'easy'),
('commission', 'An instruction to produce something in return for payment', 'The government commissioned a report on housing.', 'medium'),
('community', 'A group of people living in the same area or sharing interests', 'Local communities benefit from green spaces.', 'easy'),
('complex', 'Made of many different parts; intricate', 'The relationship between diet and health is complex.', 'easy'),
('compute', 'Calculate a figure mathematically', 'Scientists compute climate models using supercomputers.', 'medium'),
('conclude', 'Arrive at a judgement after reasoning', 'The study concludes that exercise reduces depression.', 'easy'),
('conduct', 'Carry out a particular activity', 'Researchers conducted surveys in three cities.', 'easy'),
('consequent', 'Following as a result or effect', 'The flood and the consequent disruption affected thousands.', 'hard'),
('construct', 'Build or create something', 'The bridge was constructed over five years.', 'easy'),
('consume', 'Use up a resource', 'Developed nations consume far more energy per capita.', 'easy'),
('credit', 'Publicly acknowledge a contribution', 'The discovery is credited to two independent researchers.', 'medium'),
('culture', 'The ideas and customs of a group', 'Cultural differences influence communication styles.', 'easy'),
('design', 'Decide on the look or function of something', 'The experiment was carefully designed to avoid bias.', 'easy'),
('distinction', 'A difference or contrast', 'There is an important distinction between correlation and causation.', 'medium'),
('element', 'An essential or characteristic part', 'Trust is a key element of effective teamwork.', 'easy'),
('evaluate', 'Form an idea of the amount or value of', 'Students are evaluated on both written and oral performance.', 'easy'),
('feature', 'A distinctive attribute or aspect', 'A key feature of academic writing is formal vocabulary.', 'easy'),
('final', 'Coming at the end; last', 'The final results will be published next month.', 'easy'),
('focus', 'The centre of interest or activity', 'The research focuses on childhood obesity.', 'easy'),
('impact', 'A strong effect or influence', 'The internet has had a profound impact on communication.', 'easy'),
('injure', 'Do physical harm to', 'Many workers are injured in preventable accidents each year.', 'medium'),
('institute', 'A society or organisation for a particular purpose', 'The institute publishes research on urban planning.', 'medium'),
('link', 'Make, form or suggest a connection', 'Studies link sedentary behaviour to cardiovascular disease.', 'easy'),
('locate', 'Discover the exact position of', 'Scientists located the wreck 3,000 metres below the surface.', 'medium'),
('maximise', 'Make as large as possible', 'Businesses aim to maximise profit while minimising cost.', 'medium'),
('minor', 'Lesser in importance or seriousness', 'Minor changes were made to the original proposal.', 'easy'),
('negative', 'Consisting in or characterised by absence', 'Social media can have negative effects on self-esteem.', 'easy'),
('outcome', 'The way a thing turns out; a result', 'The outcome of the experiment was unexpected.', 'easy'),
('partner', 'Associate with another in an activity', 'The two universities partnered on a joint research project.', 'easy'),
('philosophy', 'The study of the fundamental nature of knowledge and reality', 'The philosophy of the school emphasises critical thinking.', 'medium'),
('physical', 'Relating to the body rather than the mind', 'Regular physical activity improves overall wellbeing.', 'easy'),
('positive', 'Showing optimism or constructive quality', 'Exercise has a positive effect on mood.', 'easy'),
('potential', 'Having or showing the capacity to develop', 'Renewable energy has the potential to replace fossil fuels.', 'easy'),
('previous', 'Existing or occurring before in time', 'Previous research has shown a link between stress and illness.', 'easy'),
('primary', 'Of chief importance; principal', 'The primary cause of the crisis was poor regulation.', 'easy'),
('purchase', 'Acquire by paying money', 'Consumers are purchasing more goods online.', 'easy'),
('range', 'The area of variation between limits', 'A wide range of factors affect student performance.', 'easy'),
('region', 'An area, especially part of a country', 'The northern region experiences heavier rainfall.', 'easy'),
('regulate', 'Control by means of rules and regulations', 'The government regulates the pharmaceutical industry.', 'medium'),
('relevant', 'Closely connected or appropriate to the matter in hand', 'Include only evidence that is relevant to your argument.', 'easy'),
('reside', 'Have one''s permanent home in a place', 'Over 60% of the population resides in urban areas.', 'medium'),
('resource', 'A stock or supply that can be drawn on', 'Water is a precious natural resource.', 'easy'),
('restrict', 'Limit something', 'Access to the site is restricted to authorised personnel.', 'medium'),
('secure', 'Fix or obtain firmly', 'The company secured funding for the new project.', 'easy'),
('seek', 'Attempt to find or obtain', 'Many people seek employment in cities.', 'easy'),
('select', 'Carefully choose', 'Participants were selected randomly from the population.', 'easy'),
('site', 'A place where a particular event occurs', 'The construction site covers over 20 hectares.', 'easy'),
('strategy', 'A plan of action to achieve a long-term goal', 'A clear strategy is needed to reduce carbon emissions.', 'medium'),
('survey', 'Examine and record the features of an area', 'A survey of 1,000 adults revealed changing attitudes.', 'easy'),
('text', 'A book or written work', 'Academic texts require careful reading and annotation.', 'easy'),
('traditional', 'Relating to long-established customs', 'Traditional methods of farming are being replaced by modern techniques.', 'easy'),
('transfer', 'Move from one place or person to another', 'Technology transfer between countries drives innovation.', 'medium'),

-- HIGH-VALUE IELTS SPECIFIC WORDS
('ubiquitous', 'Present everywhere', 'Smartphones have become ubiquitous in modern society.', 'hard'),
('ambiguous', 'Open to multiple interpretations', 'The policy statement was ambiguous and caused confusion.', 'hard'),
('concede', 'Admit something is true after resisting', 'She conceded that the evidence was convincing.', 'hard'),
('prolific', 'Producing a large amount of something', 'She is a prolific author, publishing three novels a year.', 'hard'),
('meticulous', 'Showing great attention to detail', 'His research methodology was meticulous and thorough.', 'hard'),
('exacerbate', 'Make a problem or situation worse', 'Deforestation exacerbates the effects of climate change.', 'hard'),
('mitigate', 'Make a problem less severe or serious', 'Planting trees can help mitigate carbon emissions.', 'hard'),
('sustainable', 'Able to continue without damaging the environment', 'We need sustainable solutions to the energy crisis.', 'medium'),
('proliferate', 'Increase rapidly in number', 'Social media platforms have proliferated in recent years.', 'hard'),
('detrimental', 'Harmful or damaging to something', 'Excessive screen time can be detrimental to children''s development.', 'hard'),
('alleviate', 'Make suffering or a problem less severe', 'New medication can alleviate symptoms of chronic pain.', 'hard'),
('deteriorate', 'Become progressively worse', 'Air quality tends to deteriorate during summer months.', 'hard'),
('inevitable', 'Certain to happen; unavoidable', 'Technological change is inevitable in a modern economy.', 'medium'),
('fundamental', 'Forming a necessary base; essential', 'Education is a fundamental human right.', 'medium'),
('controversial', 'Giving rise to disagreement or debate', 'The policy was highly controversial and divided public opinion.', 'medium'),
('implication', 'A likely consequence of something', 'The implications of the study are far-reaching.', 'hard'),
('substantial', 'Of considerable importance or size', 'There was a substantial improvement in test scores.', 'medium'),
('predominantly', 'Mainly; for the most part', 'The workforce is predominantly female in this sector.', 'hard'),
('consecutive', 'Following in unbroken sequence', 'Unemployment fell for five consecutive months.', 'hard'),
('discrepancy', 'A difference between two things that should be the same', 'There is a discrepancy between the reported and actual figures.', 'hard'),
('compensate', 'Give something to make up for loss or suffering', 'Higher wages compensate for the difficult working conditions.', 'medium'),
('hypothesis', 'A proposed explanation based on limited evidence', 'The researcher tested the hypothesis through controlled experiments.', 'hard'),
('implement', 'Put a plan or decision into effect', 'The school implemented a new curriculum in September.', 'medium'),
('monitor', 'Observe and check the progress of something', 'Scientists monitor sea temperatures to track climate change.', 'medium'),
('objective', 'Not influenced by personal feelings; factual', 'Academic writing should be objective and evidence-based.', 'medium'),
('perceive', 'Become aware of through the senses or mind', 'Students often perceive grammar as the hardest part of IELTS.', 'medium'),
('profound', 'Very great or intense; having deep meaning', 'The discovery had a profound impact on medical science.', 'hard'),
('accumulate', 'Gradually gather or increase', 'Evidence has accumulated over decades to support this theory.', 'hard'),
('advocate', 'Publicly recommend or support a cause', 'Many scientists advocate for stricter emissions targets.', 'medium'),
('attribute', 'Regard something as being caused by', 'The improvement was attributed to better teaching methods.', 'hard'),
('bias', 'Prejudice in favour of or against something', 'Confirmation bias affects how people interpret evidence.', 'hard'),
('collaborate', 'Work jointly with others', 'Universities collaborate with industry to fund research.', 'medium'),
('criterion', 'A principle used to judge something (pl. criteria)', 'The main criterion for selection was academic performance.', 'hard'),
('diminish', 'Make or become less', 'The impact of the policy has diminished over time.', 'medium'),
('empirical', 'Based on observation and experiment, not theory', 'The study provides empirical evidence for the link.', 'hard'),
('facilitate', 'Make an action easier', 'Technology facilitates communication across borders.', 'medium'),
('generate', 'Produce or create', 'Wind farms generate electricity without carbon emissions.', 'easy'),
('global', 'Relating to the whole world', 'Global temperatures have risen by 1.2°C since pre-industrial times.', 'easy'),
('hierarchy', 'A system in which people are ranked above each other', 'Corporate hierarchy affects decision-making speed.', 'hard'),
('inherit', 'Receive from a predecessor', 'Future generations will inherit the consequences of today''s choices.', 'medium'),
('innovate', 'Introduce new methods or ideas', 'Companies must innovate to stay competitive.', 'medium'),
('integrate', 'Combine parts into a whole', 'Technology should be integrated into everyday teaching.', 'medium'),
('magnitude', 'The great size or extent of something', 'Scientists underestimated the magnitude of the disaster.', 'hard'),
('marginal', 'Relating to or situated at the edge; minor', 'The benefit was marginal and did not justify the cost.', 'hard'),
('mechanism', 'The way something works or is brought about', 'The mechanism by which the drug works is not fully understood.', 'hard'),
('paradigm', 'A typical example or pattern; a worldview', 'The discovery shifted the scientific paradigm.', 'hard'),
('paradox', 'A situation that seems contradictory but may be true', 'It is a paradox that richer countries often report lower happiness.', 'hard'),
('reform', 'Make changes to improve a system', 'The government proposed sweeping education reforms.', 'medium'),
('rhetoric', 'Language designed to have a persuasive effect', 'Politicians often use rhetoric rather than facts.', 'hard'),
('scenario', 'A possible sequence of events; a setting', 'The worst-case scenario involves a 4°C rise in temperature.', 'medium'),
('simultaneously', 'At the same time', 'The drug simultaneously reduces inflammation and pain.', 'hard'),
('stereotype', 'A fixed, oversimplified image of a group', 'Media stereotypes can reinforce social inequality.', 'hard'),
('subordinate', 'Lower in rank or position', 'Subordinate clauses add detail to a main idea.', 'hard'),
('tedious', 'Too long and slow; boring', 'Repetitive tasks can become tedious without variety.', 'medium'),
('transition', 'The process of changing from one state to another', 'The country is in transition from an industrial to a service economy.', 'medium'),
('trend', 'A general direction in which something is developing', 'There is a growing trend towards remote working.', 'easy'),
('undermine', 'Lessen the effectiveness, power, or ability of', 'Constant criticism can undermine a student''s confidence.', 'hard');


INSERT INTO public.vocab_words (word, definition, example, difficulty) VALUES

-- ACADEMIC WORD LIST (SUBLIST 3 & 4 HIGHLIGHTS)
('alternative', 'One of two or more available possibilities', 'Solar power provides a clean alternative to fossil fuels.', 'easy'),
('circumstance', 'A condition or fact connected with an event or action', 'Due to unforeseen circumstances, the conference was postponed.', 'medium'),
('compensate', 'Provide something to reduce or balance a bad effect', 'Higher wages compensate workers for dangerous conditions.', 'medium'),
('component', 'A part or element of a larger whole', 'Nitrogen is a key component of the earth''s atmosphere.', 'medium'),
('constrain', 'Severely limit or restrict the scope or extent of', 'Budget limitations constrain the scope of the research.', 'hard'),
('contribute', 'Give something in order to achieve or provide something', 'Many factors contribute to rising global temperatures.', 'easy'),
('convention', 'A way in which something is usually done; custom', 'The essay follows standard academic conventions.', 'medium'),
('demonstrate', 'Clearly show the existence or truth of something by evidence', 'The study demonstrates a clear link between exercise and mood.', 'easy'),
('document', 'Record something in written, photographic, or other form', 'The report documents instances of environmental damage.', 'medium'),
('dominant', 'Most important, powerful, or influential', 'English has become the dominant language in international business.', 'medium'),
('emphasis', 'Special importance, value, or prominence given to something', 'The university places strong emphasis on practical skills.', 'medium'),
('illustrate', 'Serve as an explanation or example of', 'The chart illustrates the growth of online retail.', 'easy'),
('imply', 'Indicate or suggest something without stating it directly', 'The survey results imply a shift in public sentiment.', 'medium'),
('initial', 'Existing or occurring at the beginning', 'The initial findings were promising, but required further testing.', 'easy'),
('instance', 'An example or single occurrence of something', 'There were several instances of data duplication.', 'easy'),
('interact', 'Act in such a way as to have an effect on another', 'Social media changes how young people interact with each other.', 'easy'),
('justify', 'Show or prove to be right or reasonable', 'It is difficult to justify spending public money on this project.', 'medium'),
('layer', 'A sheet, quantity, or thickness of material covering a surface', 'Ozone forms a protective layer around the Earth.', 'easy'),
('proportion', 'A part, share, or number considered in comparative relation to a whole', 'A large proportion of students work while studying.', 'medium'),
('publish', 'Prepare and issue a book, journal, or piece of work for public sale', 'The results were published in a peer-reviewed journal.', 'easy'),
('reaction', 'A response to an event or a substance', 'Public reaction to the news was overwhelmingly positive.', 'easy'),
('rely', 'Depend on with full trust or confidence', 'Many rural areas rely heavily on agriculture for income.', 'easy'),
('remove', 'Take away or eliminate something', 'Filter systems are used to remove impurities from drinking water.', 'easy'),
('scheme', 'A systematic plan or arrangement for attaining a goal', 'The city introduced a bike-sharing scheme to reduce traffic.', 'medium'),
('sequence', 'A particular order in which related events follow each other', 'DNA sequencing allows scientists to trace genetic origins.', 'medium'),
('shift', 'A slight change in position, direction, or condition', 'There has been a notable shift towards renewable energy.', 'easy'),
('specified', 'Stated clearly and explicitly', 'Applicants must submit their forms by the specified date.', 'medium'),
('sufficient', 'Enough; adequate for a specific purpose', 'The evidence is not sufficient to prove the hypothesis.', 'medium'),
('technical', 'Relating to a particular subject, art, or craft', 'The job requires specialized technical knowledge.', 'easy'),
('valid', 'Having a sound basis in logic or fact', 'The survey provided valid insights into consumer behaviour.', 'medium'),

-- TOPIC-SPECIFIC IELTS ESSENTIALS
('deforestation', 'The action of clearing a wide area of trees', 'Deforestation contributes significantly to loss of biodiversity.', 'medium'),
('urbanisation', 'The process of making an area more urban', 'Rapid urbanisation has placed pressure on city infrastructure.', 'medium'),
('biodiversity', 'The variety of plant and animal life in a habitat', 'Tropical rainforests are famous for their rich biodiversity.', 'hard'),
('infrastructure', 'The basic physical systems of a business, region, or nation', 'Investing in public transport infrastructure reduces congestion.', 'medium'),
('detriment', 'The state of being harmed or damaged', 'He worked long hours to the detriment of his health.', 'hard'),
('prevalent', 'Widespread in a particular area or at a particular time', 'Obesity is increasingly prevalent among children.', 'hard'),
('unprecedented', 'Never done or known before', 'The pandemic caused unprecedented disruption to global education.', 'hard'),
('disparity', 'A great difference or inequality', 'There is a growing disparity between urban and rural incomes.', 'hard'),
('sustainable', 'Able to be maintained at a certain rate or level without depleting resources', 'Solar energy is a sustainable alternative to coal.', 'medium'),
('monotonous', 'Lacking in variety and interest; tedious', 'Factory workers often perform monotonous tasks for hours.', 'medium'),
('obsolete', 'No longer produced or used; out of date', 'CDs have become largely obsolete due to streaming services.', 'hard'),
('cohesive', 'Forming a united whole; logically connected', 'A good essay must present a clear, cohesive argument.', 'medium'),
('paramount', 'More important than anything else; supreme', 'Student safety is of paramount importance during field trips.', 'hard'),
('deplete', 'Use up the supply or resources of', 'Overfishing threatens to deplete marine populations.', 'medium'),
('susceptible', 'Likely or liable to be influenced or harmed by a particular thing', 'Elderly people are more susceptible to winter infections.', 'hard'),
('lucrative', 'Producing a great deal of profit', 'Tech companies offer lucrative salaries to software engineers.', 'medium'),
('allocate', 'Distribute resources or duties for a specific purpose', 'Governments must allocate more funds to healthcare.', 'medium'),
('fluctuate', 'Rise and fall irregularly in number or amount', 'Oil prices tend to fluctuate based on global demand.', 'medium'),
('conducive', 'Making a certain situation or outcome likely or possible', 'A quiet environment is conducive to effective studying.', 'hard'),
('implement', 'Put a decision, plan, or agreement into effect', 'The university plans to implement online registration next year.', 'medium');